# Generated by Django 4.0.3 on 2022-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='yh'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='yh'),
        ),
        migrations.AddField(
            model_name='luntan',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='yh'),
        ),
        migrations.AddField(
            model_name='mbti',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='yh'),
        ),
        migrations.AlterField(
            model_name='luntan',
            name='jianjie',
            field=models.TextField(default='', max_length=1550, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, default='这个人什么都没有写', null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='职业或专业'),
        ),
        migrations.AlterField(
            model_name='person',
            name='school',
            field=models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.CharField(default='这个人什么都没有写', max_length=30, verbose_name='yh'),
        ),
    ]
