# Generated by Django 4.0.3 on 2022-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_disc_user_history_user_luntan_user_mbti_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='这个人什么都没有写', max_length=30, verbose_name='yh')),
                ('birth', models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='学校')),
                ('company', models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='公司')),
                ('profession', models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='职业或专业')),
                ('address', models.CharField(blank=True, default='这个人什么都没有写', max_length=100, null=True, verbose_name='住址')),
                ('about', models.TextField(blank=True, default='这个人什么都没有写', null=True, verbose_name='其他')),
            ],
        ),
    ]
