# Generated by Django 3.2 on 2022-04-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_person1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luntan',
            name='user',
            field=models.CharField(blank=True, default='admin', max_length=30, null=True, verbose_name='yh'),
        ),
        migrations.CreateModel(
            name='gongsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='企业')),
                ('jianjie', models.TextField(default='', max_length=1550, verbose_name='企业简介')),
                ('Count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userinfo')),
            ],
        ),
    ]
