# Generated by Django 3.2 on 2022-04-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220413_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='ans',
            field=models.CharField(blank=True, default='null', max_length=10000, null=True, verbose_name='结论'),
        ),
        migrations.AddField(
            model_name='mbti',
            name='ans',
            field=models.CharField(blank=True, default='null', max_length=10000, null=True, verbose_name='结论'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ba',
            field=models.SmallIntegerField(blank=True, choices=[(1, '肯定：自信，极少犹豫或者动摇'), (2, '无拘无束：不喜欢预先计划，或者被计划牵制'), (3, '羞涩：安静，不善于交谈'), (4, '有时间性：生活处事依靠时间表，不喜欢计划被人干扰')], null=True, verbose_name='第八题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='er',
            field=models.SmallIntegerField(blank=True, choices=[(3, '坚持不懈：要完成现有的事才能做新的事情'), (2, '喜好娱乐：开心充满乐趣与幽默感'), (4, '善于说服：用逻辑和事实而不用威严和权利服人'), (1, '平和：在冲突中不受干扰，保持平静')], null=True, verbose_name='第二题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershi',
            field=models.SmallIntegerField(blank=True, choices=[(2, '跳跃性：充满活力和生气勃勃'), (1, '无畏：大胆前进，不怕冒险'), (4, '规范性：时时坚持自己的举止合乎认同的道德规范'), (3, '平衡：稳定，走中间路线')], null=True, verbose_name='第二十题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershiba',
            field=models.SmallIntegerField(blank=True, choices=[(3, '平淡：平实淡漠，中间路线,无高低之分，很少表露情感'), (4, '悲观：尽管期待最好但往往首先看到事物不利之处'), (1, '自负：自我评价高，认为自己是最好的人选'), (2, '放任:许别人做他喜欢做的事情，为的是讨好别人，令别人鼓吹自己')], null=True, verbose_name='第二十八题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershier',
            field=models.SmallIntegerField(blank=True, choices=[(2, '散漫：生活任性无秩序'), (1, '无同情心：不易理解别人的问题和麻烦'), (3, '缺乏热情：不易兴奋，经常感到好事难做'), (4, '不宽恕：不易宽恕和忘记别人对自己的伤害，易嫉妒')], null=True, verbose_name='第二十二题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershijiu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '易怒：善变，孩子性格，易激动，过后马上就忘了'), (1, '无目标：不喜欢目标，也无意订目标'), (2, '好争论：易与人争吵，不管对何事都觉得自己是对的'), (4, '孤芳自赏：容易感到被疏离，经常没有安全感或担心别人不喜欢和自己相处')], null=True, verbose_name='第二十九题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershiliu',
            field=models.SmallIntegerField(blank=True, choices=[(4, '不受欢迎：由于强烈要求完美，而拒人千里'), (3, '不参与：不愿意加入，不参与，对别人生活不感兴趣'), (2, '难预测：时而兴奋，时而低落，或总是不兑现诺言'), (1, '缺同情心：很难当众表达对弱者或者受难者的情感')], null=True, verbose_name='第二十六题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershiqi',
            field=models.SmallIntegerField(blank=True, choices=[(1, '固执：坚持照自己的意见行事，不听不同意见'), (2, '随兴：做事情没有一贯性，随意做事情'), (4, '难于取悦：因为要求太高而使别人很难取悦'), (3, '行动迟缓：迟迟才行动，不易参与或者行动总是慢半拍')], null=True, verbose_name='第二十七题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, '保留：不愿意参与，尤其是当事情复杂时'), (4, '怨恨：把实际或者自己想象的别人的冒犯经常放在心中'), (1, '逆反：抗拒、或者拒不接受别人的方法，固执己见'), (2, '唠叨：重复讲同一件事情或故事，忘记已经重复多次，总是不断找话题说话')], null=True, verbose_name='第二十三题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershisi',
            field=models.SmallIntegerField(blank=True, choices=[(4, '挑剔：坚持琐事细节，总喜欢挑不足'), (3, '胆小：经常感到强烈的担心焦虑、悲戚'), (2, '健忘：缺乏自我约束，导致健忘，不愿意回忆无趣的事情'), (1, '率直：直言不讳，直接表达自己的看法')], null=True, verbose_name='第二十四题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershiwu',
            field=models.SmallIntegerField(blank=True, choices=[(1, '没耐性：难以忍受等待别人'), (4, '无安全感：感到担心且无自信心'), (2, '优柔寡断：很难下决定'), (3, '好插嘴：一个滔滔不绝的发言人，不是好听众，不注意别人的说话')], null=True, verbose_name='第二十五题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='ershiyi',
            field=models.SmallIntegerField(blank=True, choices=[(4, '乏味：死气沉沉，缺乏生气'), (3, '忸怩：躲避别人的注意力，在众人注意下不自然'), (1, '露骨：好表现，华而不实，声音大'), (2, '专横：喜命令支配，有时略显傲慢')], null=True, verbose_name='第二十一题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='jiu',
            field=models.SmallIntegerField(blank=True, choices=[(4, '迁就：改变自己以与他人协调，短时间内按他人要求行事'), (3, '井井有条：有系统有条理安排事情的人'), (1, '坦率：毫无保留，坦率发言'), (2, '乐观：令他人和自己相信任何事情都会好转')], null=True, verbose_name='第九题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='liu',
            field=models.SmallIntegerField(blank=True, choices=[(4, '生机勃勃：充满生命力与兴奋'), (1, '满足：容易接受任何情况与环境'), (2, '敏感：对周围的人事过分关心'), (3, '自立：独立性强，只依靠自己的能力、判断、与才智')], null=True, verbose_name='第六题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='qi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '计划者：先做详尽的计划，并严格要计划进行，不想改动'), (4, '耐性：不因延误而懊恼，冷静且能容忍'), (2, '积极：相信自己有转危为安的能力'), (1, '推动者：动用性格魅力或鼓励别人参与')], null=True, verbose_name='第七题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='san',
            field=models.SmallIntegerField(blank=True, choices=[(4, '顺服：易接受他人的观点和喜好，不坚持己见'), (3, '自我牺牲：为他人利益愿意放弃个人意见'), (1, '善于社交：认为与人相处是好玩，而不是挑战或者商业机会'), (2, '意志坚定：决心以自己的方式做事')], null=True, verbose_name='第三题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '天真：孩子般的单纯，不理解生命的真谛'), (1, '消极：往往看到事物的消极面阴暗面，而少有积极的态度'), (4, '鲁莽：充满自信有胆识但总是不恰当'), (2, '冷漠：漠不关心，得过且过')], null=True, verbose_name='第三十题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshiba',
            field=models.SmallIntegerField(blank=True, choices=[(3, '拖延：凡事起步慢，需要推动力'), (4, '多疑：凡事怀疑，不相信别人'), (1, '易怒：对行动不快或不能完成指定工作时易烦躁和发怒'), (2, '不专注：无法专心致志或者集中精力')], null=True, verbose_name='第三十八题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshier',
            field=models.SmallIntegerField(blank=True, choices=[(2, '过分敏感：对事物过分反应，被人误解时感到被冒犯'), (4, '不圆滑老练：经常用冒犯或考虑不周的方式表达自己'), (3, '胆怯：遇到困难退缩'), (2, '喋喋不休：难以自控，滔滔不绝，不能倾听别人')], null=True, verbose_name='第三十二题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshijiu',
            field=models.SmallIntegerField(blank=True, choices=[(4, '报复性：记恨并惩罚冒犯自己的人'), (2, '烦躁：喜新厌旧，不喜欢长时间做相同的事情'), (3, '勉强：不愿意参与或者说投入'), (1, '轻率：因没有耐心，不经思考，草率行动')], null=True, verbose_name='第三十九题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshiliu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '缓慢：行动思想均比较慢，过分麻烦'), (3, '顽固：决心依自己的意愿行事，不易被说服'), (1, '好表现：要吸引人，需要自己成为被人注意的中心'), (4, '有戒心：不易相信，对语言背后的真正的动机存在疑问')], null=True, verbose_name='第三十六题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshiqi',
            field=models.SmallIntegerField(blank=True, choices=[(2, '孤僻：需要大量的时间独处，避开人群'), (4, '统治欲：毫不犹豫地表示自己的正确或控制能力'), (3, '懒惰：总是先估量事情要耗费多少精力，能不做最好'), (1, '大嗓门：说话声和笑声总盖过他人')], null=True, verbose_name='第三十七题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, '腼腆：事事不确定，对所做的事情缺乏信心'), (2, '生活紊乱：缺乏安排生活的能力'), (1, '跋扈：冲动的控制事物和别人，指挥他人'), (4, '抑郁：常常情绪低落')], null=True, verbose_name='第三十三题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshisi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '缺乏毅力：反复无常，互相矛盾，情绪与行动不合逻辑'), (1, '内向：活在自己的世界里，思想和兴趣放在心里'), (4, '不容忍：不能忍受他人的观点、态度和做事的方式'), (2, '无异议：对很多事情漠不关心')], null=True, verbose_name='第三十四题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshiwu',
            field=models.SmallIntegerField(blank=True, choices=[(4, '杂乱无章：生活环境无秩序，经常找不到东西'), (1, '情绪化：情绪不易高涨，感到不被欣赏时很容易低落'), (3, '喃喃自语：低声说话，不在乎说不清楚'), (2, '喜操纵：精明处事，操纵事情，使对自己有利')], null=True, verbose_name='第三十五题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sanshiyi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '担忧：时时感到不确定、焦虑、心烦'), (4, '不善交际:总喜欢挑人毛病，不被人喜欢'), (1, '工作狂:为了回报或者说成就感，而不是为了完美，因而设立雄伟目标不断工作，耻于休息'), (2, '喜获认同：需要旁人认同赞赏，像演员')], null=True, verbose_name='第三十一题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shi',
            field=models.SmallIntegerField(blank=True, choices=[(1, '强迫性：发号施令，强迫他人听从'), (3, '忠诚：一贯可靠，忠心不移，有时毫无根据地奉献'), (4, '有趣：风趣，幽默，把任何事物都能变成精彩的故事'), (2, '友善：不主动交谈，不爱争论')], null=True, verbose_name='第十题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shiba',
            field=models.SmallIntegerField(blank=True, choices=[(2, '知足：满足自己拥有的，很少羡慕别人'), (4, '首领：要求领导地位及别人跟随'), (1, '制图者：用图表数字来组织生活，解决问题'), (3, '惹人喜爱：人们注意的中心，令人喜欢')], null=True, verbose_name='第十八题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shier',
            field=models.SmallIntegerField(blank=True, choices=[(3, '令人开心：充满活力，并将快乐传于他人'), (1, '文化修养：对艺术学术特别爱好，如戏剧、交响乐'), (4, '自信：确信自己个人能力与成功'), (2, '贯彻始终：情绪平稳，做事情坚持不懈')], null=True, verbose_name='第十二题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shijiu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '完美主义者：对自己、对别人都高标准、一切事物有秩序'), (4, '和气：易相处，易说话，易让人接近'), (2, '勤劳：不停的工作，完成任务，不愿意休息'), (1, '受欢迎：聚会时的灵魂人物，受欢迎的宾客')], null=True, verbose_name='第十九题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shiliu',
            field=models.SmallIntegerField(blank=True, choices=[(2, '考虑周到：善解人意，帮助别人，记住特别的日子'), (3, '执着：不达目的，誓不罢休'), (4, '多言：不断的说话、讲笑话以娱乐他人，觉得应该避免沉默而带来的的尴尬'), (1, '容忍：易接受别人的想法和看法，不需要反对或改变他人')], null=True, verbose_name='第十六题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shiqi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '聆听者：愿意听别人倾诉'), (4, '忠心对自己的理想、朋友、工作都绝对忠实，有时甚至不需要理由'), (1, '领导者：天生的领导，不相信别人的能力能比上自己'), (2, '活力充沛：充满活力，精力充沛')], null=True, verbose_name='第十七题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shisan',
            field=models.SmallIntegerField(blank=True, choices=[(2, '理想主义：以自己完美的标准来设想衡量新事物'), (4, '独立：自给自足，独立自信，不需要他人帮忙'), (3, '无攻击性：不说或者做可能引起别人不满和反对的事情'), (1, '富有激励：鼓励别人参与、加入，并把每件事情变得有趣')], null=True, verbose_name='第十三题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shisi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '感情外露：从不掩饰情感.喜好,交谈时常身不由己接触他人'), (1, '深沉：深刻并常常内省，对肤浅的交谈、消遣会厌恶'), (4, '果断：有很快做出判断与结论的能力'), (2, '幽默：语气平和而有冷静的幽默')], null=True, verbose_name='第十四题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shiwu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '调解者：经常居中调节不同的意见，以避免双方的冲突'), (4, '音乐性：爱好参与并有较深的鉴赏能力，因音乐的艺术性,而不是因为表演的乐趣'), (1, '发起人：高效率的推动者，是他人的领导者，闲不住'), (2, '喜交朋友：喜欢周旋聚会中，善交新朋友不把任何人当陌生人')], null=True, verbose_name='第十五题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='shiyi',
            field=models.SmallIntegerField(blank=True, choices=[(1, '勇敢：敢于冒险，无所畏惧'), (4, '体贴：待人得体，有耐心'), (2, '注意细节：观察入微，做事情有条不紊'), (3, '可爱：开心，与他人相处充满乐趣')], null=True, verbose_name='第十一题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='si',
            field=models.SmallIntegerField(blank=True, choices=[(3, '使人认同：因人格魅力或性格使人认同'), (1, '体贴：关心别人的感受与需要'), (4, '竞争性：把一切当作竞赛，总是有强烈的赢的欲望'), (2, '自控性：控制自己的情感，极少流露')], null=True, verbose_name='第四题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='sishi',
            field=models.SmallIntegerField(blank=True, choices=[(3, '妥协：为避免矛盾即使自己是对的也不惜放弃自己的立场'), (4, '好批评：不断地衡量和下判断，经常考虑提出反对意见'), (1, '狡猾：精明，总是有办法达到目的'), (2, '善变：像孩子般注意力短暂，需要各种变化，怕无聊')], null=True, verbose_name='第四十题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='wu',
            field=models.SmallIntegerField(blank=True, choices=[(3, '使人振作：给他人清新振奋的刺激'), (1, '尊重他人：对人诚实尊重'), (4, '善于应变：对任何情况都能作出有效的反应'), (2, '含蓄：自我约束情绪与热忱')], null=True, verbose_name='第五题'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='yi',
            field=models.SmallIntegerField(blank=True, choices=[(1, '富于冒险:愿意面对新事物并敢于下决心掌握的人'), (3, '适应力强:轻松自如适应任何环境'), (2, '生动:充满活力,表情生动,多手势'), (4, '善于分析:喜欢研究各部分之间的逻辑和正确的关系')], null=True, verbose_name='第一题'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ba',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E容易让人了解'), (2, 'I难于让人了解')], null=True, verbose_name='你是否'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F仁慈慷慨的'), (5, 'T意志坚定的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashiba',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F同情'), (5, 'T分析')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashier',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S制作'), (4, 'N设计')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashijiu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T坚持己见'), (6, 'F温柔有爱心')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashiliu',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S制造'), (4, 'N创造')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashiqi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N新颖的'), (3, 'S已知的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashisan',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N可能性'), (3, 'S必然性')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashisi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F温柔'), (5, 'T力量')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashiwu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T实际'), (6, 'F多愁善感')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='bashiyi',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T公正的'), (6, 'F有关怀心')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='er',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P较为随兴所至的人'), (7, 'J较为有条理的人')], null=True, verbose_name='你认为自己是一个'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershi',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J很早便把约会、社交聚集等事情安排妥当'), (8, 'P无拘无束，看当时有什么好玩就做什么')], null=True, verbose_name='你比较喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershiba',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J预先安排的'), (8, 'P无计划的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershier',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I有时感到郁闷'), (1, 'E常常乐在其中')], null=True, verbose_name='在社交聚会中，你'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershijiu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N抽象'), (3, 'S具体')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershiliu',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I要花很长时间才认识你'), (1, 'E用很短的时间便认识你')], null=True, verbose_name='你认为别人一般'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershiqi',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I注重隐私'), (1, 'E坦率开放')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershisan',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E和别人容易混熟'), (2, 'I趋向自处一隅')], null=True, verbose_name='你通常'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershisi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N一个思想敏捷及非常聪颖的人'), (3, 'S实事求是，具丰富常识的人')], null=True, verbose_name='哪些人会更吸引你？'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershiwu',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P颇为喜欢处理迫使你分秒必争的突发'), (7, 'J通常预先计划，以免要在压力下工作')], null=True, verbose_name='在日常工作中，你会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='ershiyi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P大部分的时间都是跟当天的感觉行事'), (7, 'J事先知道大部分的日子会做什么')], null=True, verbose_name='计划一个旅程时，你较喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='jiu',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J合你心意'), (8, 'P令你感到束缚')], null=True, verbose_name='按照程序表做事'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='jiushi',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S具体的'), (4, 'N抽象的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='jiushier',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T能干'), (6, 'F仁慈')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='jiushisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S实际'), (4, 'N创新')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='jiushiyi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F全心投入'), (5, 'T有决心的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liu',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F你的情感支配你的理智'), (5, 'T你的理智主宰你的情感')], null=True, verbose_name='你是否经常让'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushi',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I与某些人很难打开话匣儿和保持对话'), (1, 'E与多数人都能从容地长谈')], null=True, verbose_name='在社交场合中，你经常会感到'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushiba',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J合你意'), (8, 'P使你提不起劲')], null=True, verbose_name='把周末期间要完成的事列成清单，这个主意会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushier',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E马上可以'), (2, 'I要待他们真正了解你之后才可以')], null=True, verbose_name='你刚认识的朋友能否说出你的兴趣'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushijiu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T能干的'), (6, 'F富有同情心')], null=True, verbose_name='哪个是较高的赞誉，或称许为'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushiliu',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I跟你很熟悉的个别人谈话'), (1, 'E参与大伙的谈话')], null=True, verbose_name='和一群人在一起，你通常会选'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushiqi',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E是说话很多的一个'), (2, 'I让别人多说话')], null=True, verbose_name='在社交聚会上，你会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushisan',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N讲授概念和原则的'), (3, 'S讲授事实和数据的')], null=True, verbose_name='你通常较喜欢的科目是'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushisi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F一贯感性的人'), (5, 'T一贯理性的人')], null=True, verbose_name='哪个是较高的赞誉，或称许为'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushiwu',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P有时是需要的，但一般来说你不大喜欢这样做'), (7, 'J大多数情况下是有帮助而且是你喜欢做的')], null=True, verbose_name='你认为按照程序表做事'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='liushiyi',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S按照一般认可的方法去做'), (4, 'N构想一个自己的想法')], null=True, verbose_name='要做许多人也做的事，你比较喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P凭兴所至行事'), (7, 'J按照计划行事')], null=True, verbose_name='处理许多事情上，你会喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishi',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J事先安排你的社交约会'), (8, 'P随兴之所至做事')], null=True, verbose_name='你通常喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishiba',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T据事实衡量'), (6, 'F考虑他人的感受和意见')], null=True, verbose_name='要作决定时，你认为比较重要的是'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishier',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I只限于跟你有共同兴趣的人'), (1, 'E几乎跟任何人都可以')], null=True, verbose_name='你能否滔滔不绝地与人聊天'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishijiu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N想象的'), (3, 'S真实的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishiliu',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P按当天心情去做'), (7, 'J照拟好的程序表去做')], null=True, verbose_name='你做事多数是'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishiqi',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E可以和任何人按需求从容地交谈'), (2, 'I只是对某些人或在某种情况下才可以畅所欲言')], null=True, verbose_name='你是否'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S跟随一些证明有效的方法'), (4, 'N分析还有什么毛病，及针对尚未解决的难题')], null=True, verbose_name='你会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishisi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N喜欢奇特或创新的表达方式'), (3, 'S喜欢作者直话直说')], null=True, verbose_name='为乐趣而阅读时，你会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishiwu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T天性淳良，但常常前后不一的'), (4, 'N言词尖锐但永远合乎逻辑的')], null=True, verbose_name='你宁愿替哪一类上司（或者老师）工作？'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='qishiyi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P边做边想该做什么'), (7, 'J首先把工作按步细分')], null=True, verbose_name='总的说来，要做一个大型作业时，你会选'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='san',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S以事实为主的课程'), (4, 'N涉及理论的课程')], null=True, verbose_name='假如你是一位老师，你会选教'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F温柔'), (5, 'T坚定')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshiba',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F敏感'), (5, 'T公正')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshier',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S事实'), (4, 'N意念')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshijiu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T令人信服'), (6, 'F感人的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshiliu',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J有系统'), (8, 'P随意')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshiqi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N理论'), (3, 'S肯定')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshisan',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P冲动'), (7, 'J决定')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshisi',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E热衷'), (2, 'I文静')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshiwu',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I文静'), (1, 'E外向')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sanshiyi',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T思考'), (6, 'F感受')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shi',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J开始前小心组织计划'), (8, 'P边做边找须做什么')], null=True, verbose_name='当你有一份特别的任务，你会喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shiba',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I一个人独处'), (1, 'E合别人在一起')], null=True, verbose_name='你喜欢花很多的时间'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shier',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I重视自我隐私的人'), (1, 'E非常坦率开放的人')], null=True, verbose_name='大多数人会说你是一个'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shijiu',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E令你活力培增'), (2, 'I常常令你心力憔悴')], null=True, verbose_name='与很多人一起会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shiliu',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F重视感情多于逻辑'), (5, 'T重视逻辑多于感情')], null=True, verbose_name='你倾向'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shiqi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P坐观事情发展才作计划'), (7, 'J很早就作计划')], null=True, verbose_name='你比较喜欢'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S实事求是的人'), (4, 'N机灵的人')], null=True, verbose_name='你宁愿被人认为是一个'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shisi',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E你介绍大家认识'), (2, 'I别人介绍你')], null=True, verbose_name='在一大群人当中，通常是'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shiwu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N常提出新注意的'), (3, 'S脚踏实地的')], null=True, verbose_name='你会跟哪些人做朋友'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='shiyi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P顺其自然'), (7, 'J按程序表做事')], null=True, verbose_name='在大多数情况下，你会选择'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='si',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'E与人容易混熟'), (2, 'I比较沉静或矜持')], null=True, verbose_name='你通常'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishi',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S声明'), (4, 'N概念')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishiba',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I朋友不多'), (1, 'E朋友众多')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishier',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I矜持'), (1, 'E健谈')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishijiu',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J有系统'), (8, 'P即兴')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishiliu',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T利益'), (6, 'F祝福')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishiqi',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S务实的'), (4, 'N理论的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishisan',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J有条不紊'), (8, 'P不拘小节')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishisi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N意念'), (3, 'S实况')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishiwu',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F同情怜悯'), (5, 'T远见')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='sishiyi',
            field=models.SmallIntegerField(blank=True, choices=[(8, 'P不受约束'), (7, 'J预先安排')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N富于想象力的人'), (3, 'S现实的人')], null=True, verbose_name='一般来说，你和哪些人比较合得来？'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushi',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N富想象的'), (3, 'S以事论事')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushiba',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S合情合理'), (4, 'N令人着迷')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushier',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T客观的'), (6, 'F热情的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushijiu',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J把要做的不同工作依次列出'), (8, 'P马上动工')], null=True, verbose_name='当你要在一个星期内完成一个大项目，你在开始的时候会'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushiliu',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F富同情'), (5, 'T合逻辑')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushiqi',
            field=models.SmallIntegerField(blank=True, choices=[(5, 'T具分析力'), (6, 'F多愁善感')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushisan',
            field=models.SmallIntegerField(blank=True, choices=[(3, 'S建造'), (4, 'N发明')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushisi',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'I文静'), (1, 'E爱合群')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushiwu',
            field=models.SmallIntegerField(blank=True, choices=[(4, 'N理论'), (3, 'S事实')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='wushiyi',
            field=models.SmallIntegerField(blank=True, choices=[(6, 'F亲切的'), (5, 'T客观的')], null=True, verbose_name='哪一个词语更合你心意'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='yi',
            field=models.SmallIntegerField(blank=True, choices=[(7, 'J计划你要做什么和在什么时候做'), (8, 'P说去就去')], null=True, verbose_name='当你要外出一整天，你会'),
        ),
    ]
