# Generated by Django 3.2 on 2022-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220413_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='luntan',
            name='shuxing',
            field=models.SmallIntegerField(choices=[(1, '转载链接'), (2, '原创')], default=1, verbose_name='属性'),
            preserve_default=False,
        ),
    ]
